export const LOGIN_TYPE = {
    ACCOUNT: '账户登录',
    PHONE: '手机登录',
    ACCOUNT_AND_PHONE: 'ANY'
}
export const FORM_TYPE = {
    ACCOUNT: 'account',
    PHONE: 'phone',
}

// 订单状态样式
export const ORDER_STATUS = {
    0: (name) => <span style={{ textAlign: 'center' }}><i style={{
        display: 'inline-block',
        width: '20px',
        height: '20px',
        padding: '5px',
        backgroundColor: '#f9dbc5',
        color: '#f9dbc5',
        top: '5px',
        position: 'relative',
        marginRight: '8px',
        borderRadius: '5px',
    }}><i style={{
        display: 'inline-block',
        width: '8px',
        height: '8px',
        backgroundColor: '#d28552',
        color: '#d28552',
        top: '-7px',
        position: 'relative',
        // marginRight: '8px',
        borderRadius: '8px',
    }}></i></i>{name || '已超时'}</span>,
    1: (name) => <span style={{ textAlign: 'center' }}><i style={{
        display: 'inline-block',
        width: '20px',
        height: '20px',
        padding: '5px',
        backgroundColor: '#deecec',
        color: '#deecec',
        top: '5px',
        position: 'relative',
        marginRight: '8px',
        borderRadius: '4px',
    }}><i style={{
        display: 'inline-block',
        width: '8px',
        height: '8px',
        backgroundColor: '#437876',
        color: '#437876',
        top: '-7px',
        position: 'relative',
        // marginRight: '8px',
        borderRadius: '8px',
    }}></i></i>{name || '已完成'}</span>,
    2: (name) => <span style={{ textAlign: 'center' }}><i style={{
        display: 'inline-block',
        width: '20px',
        height: '20px',
        padding: '5px',
        backgroundColor: 'orange',
        color: 'orange',
        top: '5px',
        position: 'relative',
        marginRight: '8px',
        borderRadius: '4px',
    }}><i style={{
        display: 'inline-block',
        width: '8px',
        height: '8px',
        backgroundColor: 'white',
        color: 'white',
        top: '-7px',
        position: 'relative',
        // marginRight: '8px',
        borderRadius: '8px',
    }}></i></i>{name || '已取消'}</span>,
    3: (name) => <span style={{ textAlign: 'center' }}><i style={{
        display: 'inline-block',
        width: '20px',
        height: '20px',
        padding: '5px',
        backgroundColor: 'black',
        color: 'black',
        top: '5px',
        position: 'relative',
        marginRight: '8px',
        borderRadius: '4px',
    }}><i style={{
        display: 'inline-block',
        width: '8px',
        height: '8px',
        backgroundColor: 'yellow',
        color: 'yellow',
        top: '-7px',
        position: 'relative',
        // marginRight: '8px',
        borderRadius: '8px',
    }}></i></i>{name || '待付款'}</span>,
    4: (name) => <span style={{ textAlign: 'center' }}><i style={{
        display: 'inline-block',
        width: '20px',
        height: '20px',
        padding: '5px',
        backgroundColor: '#d3eedd',
        color: '#d3eedd',
        top: '5px',
        position: 'relative',
        marginRight: '8px',
        borderRadius: '4px',
    }}><i style={{
        display: 'inline-block',
        width: '8px',
        height: '8px',
        backgroundColor: '#3f552d',
        color: '#3f552d',
        top: '-7px',
        position: 'relative',
        // marginRight: '8px',
        borderRadius: '8px',
    }}></i></i>{name || '待发货'}</span>,
    5: (name) => <span style={{ textAlign: 'center' }}><i style={{
        display: 'inline-block',
        width: '20px',
        height: '20px',
        padding: '5px',
        backgroundColor: '#d3eefd',
        color: '#d3eefd',
        top: '5px',
        position: 'relative',
        marginRight: '8px',
        borderRadius: '4px',
    }}><i style={{
        display: 'inline-block',
        width: '8px',
        height: '8px',
        backgroundColor: '#3f55cd',
        color: '#3f55cd',
        top: '-7px',
        position: 'relative',
        // marginRight: '8px',
        borderRadius: '8px',
    }}></i></i>{name || '待收货'}</span>,
    6: (name) => <span style={{ textAlign: 'center' }}><i style={{
        display: 'inline-block',
        width: '20px',
        height: '20px',
        padding: '5px',
        backgroundColor: '#aaaecd',
        color: '#aaaecd',
        top: '5px',
        position: 'relative',
        marginRight: '8px',
        borderRadius: '4px',
    }}><i style={{
        display: 'inline-block',
        width: '8px',
        height: '8px',
        backgroundColor: '#aa00fd',
        color: '#aa00fd',
        top: '-7px',
        position: 'relative',
        // marginRight: '8px',
        borderRadius: '8px',
    }}></i></i>{name || '退款中'}</span>,
}